marketo_base_url:
  default: "//lp.netwrix.com"
  description: "The base URL for your Marketo instance (e.g., //lp.netwrix.com)"

marketo_munchkin_id:
  default: "130-MAN-089"
  description: "Your Marketo Munchkin ID"
